# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class LoggerTxt < Formula
  desc "A simple command-line logging tool for daily activity tracking"
  homepage "https://github.com/grantlucas/Logger-TXT"
  version "3.1.0"
  license "GPL-3.0-or-later"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/grantlucas/Logger-TXT/releases/download/v3.1.0/logger-txt_Darwin_x86_64.tar.gz"
      sha256 "b99a982540e68f65dfff140dd4128e3c82172b05dcbdcb6fd06d5c0d040e2ce7"

      define_method(:install) do
        bin.install "logger-txt"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/grantlucas/Logger-TXT/releases/download/v3.1.0/logger-txt_Darwin_arm64.tar.gz"
      sha256 "dae78e322c24c287d747874e190da4d7c35f0bd58d3dab53cb45d7ff0524a29b"

      define_method(:install) do
        bin.install "logger-txt"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/grantlucas/Logger-TXT/releases/download/v3.1.0/logger-txt_Linux_x86_64.tar.gz"
      sha256 "906da2bdd2d6d1e20adf8121c09976944af33e17c8107b16ff1d29ea4a7b00b3"
      define_method(:install) do
        bin.install "logger-txt"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/grantlucas/Logger-TXT/releases/download/v3.1.0/logger-txt_Linux_arm64.tar.gz"
      sha256 "84e127767c864a252f536191613a398527989e599ded292238a0819081e6b492"
      define_method(:install) do
        bin.install "logger-txt"
      end
    end
  end

  test do
    system bin/"logger-txt", "version"
  end
end
