# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class LoggerTxt < Formula
  desc "A simple command-line logging tool for daily activity tracking"
  homepage "https://github.com/grantlucas/Logger-TXT"
  version "3.1.1"
  license "GPL-3.0-or-later"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/grantlucas/Logger-TXT/releases/download/v3.1.1/logger-txt_Darwin_x86_64.tar.gz"
      sha256 "67905db648e505d394e107070729e470995703ee12e745bdc82ec4fe1e2d4ae2"

      define_method(:install) do
        bin.install "logger-txt"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/grantlucas/Logger-TXT/releases/download/v3.1.1/logger-txt_Darwin_arm64.tar.gz"
      sha256 "18642b1075022299e239d82801efebeb6661ef73b1411d48a2f8641dcc14bca7"

      define_method(:install) do
        bin.install "logger-txt"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/grantlucas/Logger-TXT/releases/download/v3.1.1/logger-txt_Linux_x86_64.tar.gz"
      sha256 "058539ee0ee6efedbcc7b28215abd28b4a3a1c0537316fc93e03a92a5dd0f20f"
      define_method(:install) do
        bin.install "logger-txt"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/grantlucas/Logger-TXT/releases/download/v3.1.1/logger-txt_Linux_arm64.tar.gz"
      sha256 "a0bba69cf533d80722aebba7d7c68e9943b4896c258073cc7f2d44daaa180ed8"
      define_method(:install) do
        bin.install "logger-txt"
      end
    end
  end

  test do
    system bin/"logger-txt", "version"
  end
end
