# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Loom < Formula
  desc "A terminal UI for exploring beads issue dependencies"
  homepage "https://github.com/grantlucas/loom"
  version "1.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/grantlucas/loom/releases/download/v1.0.1/loom_Darwin_x86_64.tar.gz"
      sha256 "03df84b4049df950602342553e168ab397fcb1f2fe85a282e37edce5f0d86c11"

      define_method(:install) do
        bin.install "loom"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/grantlucas/loom/releases/download/v1.0.1/loom_Darwin_arm64.tar.gz"
      sha256 "1251a69e31dec2161b6e2b55c7f6f8280744328a51070304c6f106ed0b87f6af"

      define_method(:install) do
        bin.install "loom"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/grantlucas/loom/releases/download/v1.0.1/loom_Linux_x86_64.tar.gz"
      sha256 "a1732bf40fd77344a77a62f249023a443cb7665e851ae60cc69631a6b9a426c9"
      define_method(:install) do
        bin.install "loom"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/grantlucas/loom/releases/download/v1.0.1/loom_Linux_arm64.tar.gz"
      sha256 "76b946ae9fcc30ded8e668d435dfc7f414b65a6f821f72faccc070ce20cdf9d2"
      define_method(:install) do
        bin.install "loom"
      end
    end
  end

  test do
    system bin/"loom", "--version"
  end
end
