# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Loom < Formula
  desc "A terminal UI for exploring beads issue dependencies"
  homepage "https://github.com/grantlucas/loom"
  version "1.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/grantlucas/loom/releases/download/v1.1.0/loom_Darwin_x86_64.tar.gz"
      sha256 "41a6496c4ae13e033b188801575f2462041b8b6a775049b98bda1a98afacb65f"

      define_method(:install) do
        bin.install "loom"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/grantlucas/loom/releases/download/v1.1.0/loom_Darwin_arm64.tar.gz"
      sha256 "5feed141bf637faf5e24080deddcb7d849d11812fa10fe87766fd020663ad410"

      define_method(:install) do
        bin.install "loom"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/grantlucas/loom/releases/download/v1.1.0/loom_Linux_x86_64.tar.gz"
      sha256 "6025eaa35ca3c803851ff39c8015c49ba033b65c8697923470ef9c4a3557e248"
      define_method(:install) do
        bin.install "loom"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/grantlucas/loom/releases/download/v1.1.0/loom_Linux_arm64.tar.gz"
      sha256 "4a3fbbe454c46b1bfe3f7b2349928d8da953cb8a4879a494e4d3a8e9dc571542"
      define_method(:install) do
        bin.install "loom"
      end
    end
  end

  test do
    system bin/"loom", "--version"
  end
end
